// AUTO-GENERATED by scripts/build-data.mjs — do not edit by hand.
import type { Project } from "@/types";

export const projects: Project[] = [
  {
    "slug": "summer-vibes-festival-campaign",
    "category": "Graphic Design",
    "title": "Summer Vibes Festival Campaign",
    "description": "Created promotional materials for the \"Summer Vibes Festival,\" including posters, flyers, and social media graphics.",
    "cover": "/images/cms/w08JBQPFYIq2vr4OfcD9W6vxEug.jpeg",
    "year": "2024",
    "industry": "Event / Festival",
    "client": "FestivalWorks",
    "duration": "6 weeks",
    "featured": true,
    "sections": [
      {
        "heading": "Problem",
        "paragraphs": [
          "Promoting summer festivals in a saturated market is a significant challenge, as audiences are constantly bombarded with event advertisements across multiple channels. Many festival campaigns struggle to capture attention or convey a unique, memorable atmosphere, resulting in low engagement and ticket sales.",
          "The \"Summer Vibes Festival\" needed a cohesive visual campaign that would instantly evoke the energy and excitement of summer, while standing out from competing events."
        ],
        "images": [
          "/images/cms/7i3y7S8hh5RjwFKy8VAstpXwRLM.jpeg"
        ]
      },
      {
        "heading": "Solution",
        "paragraphs": [
          "To address this, a vibrant and cohesive set of promotional materials was developed, including posters, flyers, and social media graphics. The campaign leveraged bold, sun-soaked color palettes, playful typography, and dynamic imagery that captured the essence of summer fun.",
          "Consistent visual elements and messaging were used across all materials to reinforce the festival’s brand identity and create a unified, easily recognizable look. The designs were tailored for both print and digital platforms, ensuring maximum reach and adaptability."
        ],
        "images": [
          "/images/cms/lUKY3v1xTIvOuK62nRDiv3v87gc.jpeg",
          "/images/cms/uOR0RXqCvncnJFhOe6kPbaE9XLU.jpeg"
        ]
      },
      {
        "heading": "Challenge",
        "paragraphs": [
          "The main challenge was to create visuals that would appeal to a broad, diverse audience while maintaining a distinctive festival identity. Striking the right balance between energetic visuals and clear, informative content was essential to avoid overwhelming viewers or diluting key messages.",
          "Adapting the campaign’s look and feel for different formats—ranging from large posters to small social media posts—required careful planning to ensure visual consistency and impact at every scale."
        ],
        "images": []
      },
      {
        "heading": "Summary",
        "paragraphs": [
          "The \"Summer Vibes Festival Campaign\" successfully captured the lively spirit of summer through a series of eye-catching promotional materials. By combining vibrant colors, playful design elements, and cohesive branding, the campaign generated excitement and anticipation for the event.",
          "This project demonstrates how thoughtful, well-executed design can elevate an event’s visibility, attract a wider audience, and create a memorable festival experience from the very first impression."
        ],
        "images": [
          "/images/cms/EITi5QTOPWfDXwQq1KDpx3O7xtc.jpeg",
          "/images/cms/IEHi1D1Kw4OMU5XdXNGshH3JpU.jpeg"
        ]
      }
    ]
  },
  {
    "slug": "coral-spiral-abstract",
    "category": "Branding",
    "title": "Coral Spiral Abstract",
    "description": "A visually striking 3D abstract artwork featuring a coral-colored spiral form with smooth, flowing curves and a soft pink gradient background, emphasizing modern digital aesthetics and organic geometry.",
    "cover": "/images/cms/qbjsnnvP9w7UaA2syp36oUe8OSo.jpg",
    "year": "2025",
    "industry": "Beauty",
    "client": "VisualForms Studio",
    "duration": "3 weeks",
    "featured": true,
    "sections": [
      {
        "heading": "Problem",
        "paragraphs": [
          "In the world of digital art, it can be difficult to create abstract compositions that are both visually captivating and harmonious. Many 3D artworks either lack a sense of organic flow or fail to stand out due to uninspired color choices."
        ],
        "images": [
          "/images/cms/GXMr7UYyjAl3Onda9G2r7zW7iD0.jpg"
        ]
      },
      {
        "heading": "Solution",
        "paragraphs": [
          "This project introduces a 3D abstract artwork centered on a coral-colored spiral form with smooth, flowing curves. Set against a soft pink gradient background, the design leverages organic geometry to create a sense of movement and depth.",
          "The use of coral tones brings warmth and vibrancy, while the gentle gradient enhances the overall softness and modern appeal. This composition aims to capture attention while remaining elegant and balanced."
        ],
        "images": [
          "/images/cms/flsR6xqfDebWKrEfwDLKRuYU.jpg",
          "/images/cms/ZN2ayLXMera7geLQGafIWj94c.jpg"
        ]
      },
      {
        "heading": "Challenge",
        "paragraphs": [
          "One of the main challenges is achieving a seamless blend between the spiral’s organic curves and the digital medium’s precision. The artwork must avoid appearing too mechanical or artificial, instead highlighting the natural, fluid qualities of the spiral.",
          "Another challenge is ensuring the coral color remains vivid and harmonious with the background gradient, avoiding any visual clash or loss of contrast. Maintaining visual interest without overcrowding the composition is also essential."
        ],
        "images": []
      },
      {
        "heading": "Summary",
        "paragraphs": [
          "\"Coral Spiral Abstract\" is a visually striking 3D artwork that fuses modern digital aesthetics with organic forms. Through the interplay of a coral-colored spiral and a soft pink gradient background, the piece delivers a sense of movement, warmth, and sophistication.",
          "This project demonstrates how thoughtful use of color and form can create digital art that is both contemporary and emotionally engaging."
        ],
        "images": [
          "/images/cms/Rj0Ez5VU0m6neoNfeFEWpHKlG4.jpg"
        ]
      }
    ]
  },
  {
    "slug": "shopease-redesign-sprint",
    "category": "UI / UX Design",
    "title": "ShopEase Redesign Sprint",
    "description": "Redesigned the \"ShopEase\" e-commerce app to enhance user experience. Focused on simplifying navigation, optimizing the checkout process, and incorporating a sleek.",
    "cover": "/images/cms/nTU7b0ZAdWdlqCI4mQ4tGTPpDs.jpeg",
    "year": "2025",
    "industry": "E-commerce",
    "client": "ShopEase",
    "duration": "3 weeks",
    "featured": true,
    "sections": [
      {
        "heading": "Problem",
        "paragraphs": [
          "The original ShopEase e-commerce app faced several usability issues that hindered user satisfaction and conversion rates. Users found the navigation confusing, the checkout process cumbersome, and the overall interface outdated compared to modern e-commerce standards.",
          "These pain points resulted in higher bounce rates, abandoned carts, and a lack of customer loyalty, highlighting the urgent need for a comprehensive redesign."
        ],
        "images": [
          "/images/cms/qWjMf5YLDsHPfWrxindJlbU8dZ0.jpg"
        ]
      },
      {
        "heading": "Solution",
        "paragraphs": [
          "The redesign sprint focused on creating a more intuitive and visually appealing user experience. Navigation was simplified with a clear, consistent menu structure and prominent search functionality, allowing users to find products quickly and easily. The checkout process was streamlined by reducing unnecessary steps, providing clear progress indicators, and integrating popular payment options for convenience.",
          "The new interface adopted a sleek, modern aesthetic with ample white space, clean typography, and cohesive color schemes, making the app feel both fresh and trustworthy."
        ],
        "images": [
          "/images/cms/AQyIdhIsQfYxzXoj7uBtxQZiY.jpeg",
          "/images/cms/WzuGQPTkqf3192clNgTajkHRqk.jpeg"
        ]
      },
      {
        "heading": "Challenge",
        "paragraphs": [
          "One of the main challenges was balancing the need for a modern, minimalist look with the requirement to display a large amount of product information and features. Ensuring that the app remained easy to use for both new and returning customers required extensive user testing and iteration."
        ],
        "images": []
      },
      {
        "heading": "Summary",
        "paragraphs": [
          "The \"ShopEase Redesign Sprint\" transformed the e-commerce app into a user-friendly and visually engaging platform. By simplifying navigation, optimizing the checkout flow, and introducing a sleek new interface, the project significantly improved user satisfaction and reduced friction throughout the shopping journey.",
          "This redesign demonstrates the power of thoughtful UX/UI improvements in driving business success and enhancing the overall customer experience."
        ],
        "images": [
          "/images/cms/V3dM8G5w3WsDaQWdlZHWXxDIrvw.jpeg"
        ]
      }
    ]
  },
  {
    "slug": "black-geometric-prisms",
    "category": "Branding",
    "title": "Black Geometric Prisms",
    "description": "A collection of sharp, angular black prisms floating against a gradient dark background, showcasing a modern and sophisticated approach to digital 3D geometric composition.",
    "cover": "/images/cms/2nWXrWvPxxMHSpsOkNYf8KjzP7Q.jpeg",
    "year": "2025",
    "industry": "Tech",
    "client": "Studio Prism",
    "duration": "4 weeks",
    "featured": true,
    "sections": [
      {
        "heading": "Problem",
        "paragraphs": [
          "In the realm of digital 3D art, it is often challenging to create compositions that convey both modern sophistication and visual intrigue without overwhelming the viewer. Many geometric designs either lack depth and subtlety or become too visually complex, losing their elegance."
        ],
        "images": [
          "/images/cms/DLbVxsYll4feLhrOA8Pq4MPaVhs.jpeg"
        ]
      },
      {
        "heading": "Solution",
        "paragraphs": [
          "This project proposes a collection of sharp, angular black prisms, artfully arranged to float against a gradient dark background. By leveraging the interplay of light, shadow, and reflective surfaces, the composition achieves a sense of depth and refinement.",
          "The use of monochromatic black tones ensures a minimalist yet powerful aesthetic, while the geometric forms provide structure and visual interest. This approach allows for versatility, making the visuals suitable for a wide range of modern digital applications."
        ],
        "images": [
          "/images/cms/7vdKfhDeY9XcYH1lKpvTLMT0gb8.jpeg",
          "/images/cms/axOfqlt1OrF9ee8oXYdukDuM99U.jpeg"
        ]
      },
      {
        "heading": "Challenge",
        "paragraphs": [
          "One of the main challenges is achieving a harmonious balance between complexity and simplicity. The prisms must be arranged in a way that feels dynamic and engaging, yet not chaotic or cluttered."
        ],
        "images": []
      },
      {
        "heading": "Summary",
        "paragraphs": [
          "\"Black Geometric Prisms\" is a digital 3D art project that explores the fusion of minimalism and sophistication through the use of angular black prisms set against a gradient dark background.",
          "By focusing on clean geometric forms and nuanced lighting, the project delivers a modern visual language that is both elegant and versatile."
        ],
        "images": [
          "/images/cms/iS2DgXxnjtQqDJ5KVOdKGQLXgD8.jpeg",
          "/images/cms/8sl9Ujll2IskiALuyKBBhJlknJ4.jpeg"
        ]
      }
    ]
  },
  {
    "slug": "pantone-very-peri-poster-design",
    "category": "Graphic Design",
    "title": "Pantone Very Peri Poster Design",
    "description": "A minimalist poster design inspired by Pantone’s Color of the Year 2022, Very Peri, combining clean typography, a soft periwinkle background, and a delicate blue branch illustration for a fresh, contemporary look.",
    "cover": "/images/cms/RFcUbpIGFydbU9WBSTc9HJRQI.jpeg",
    "year": "2024",
    "industry": "Creative Agency",
    "client": "ColorTrend Agency",
    "duration": "2 weeks",
    "featured": false,
    "sections": [
      {
        "heading": "Problem",
        "paragraphs": [
          "Many poster designs that incorporate trending colors tend to become visually overwhelming or fail to capture the unique character of the chosen shade. Designers often struggle to balance color, illustration, and typography in a way that feels modern, fresh, and true to the spirit of Pantone’s Color of the Year.",
          "There is a need for a poster that highlights Very Peri’s vibrancy while maintaining a minimalist and contemporary aesthetic."
        ],
        "images": [
          "/images/cms/U0I500EmGOZ2lvygkGIvmr13JU.jpeg"
        ]
      },
      {
        "heading": "Solution",
        "paragraphs": [
          "This project proposes a minimalist poster design that uses Pantone’s Very Peri as the primary background color. Clean, modern typography is paired with a subtle blue branch illustration, creating a harmonious focal point.",
          "The overall composition is kept simple to let the color and illustration breathe, ensuring that the freshness and optimism of Very Peri are front and center. This approach delivers a poster that is both visually striking and elegantly understated."
        ],
        "images": [
          "/images/cms/mBc2xUjTRVxlcztYHtgXYF11o.jpeg",
          "/images/cms/HNVCqnaFAfiDAhkxkg4SjB5c3w.jpeg"
        ]
      },
      {
        "heading": "Challenge",
        "paragraphs": [
          "The main challenge lies in achieving the right balance between minimalism and visual interest. It is crucial to ensure that the poster does not appear too plain or empty, while still avoiding clutter.",
          "The typography must complement the illustration without overpowering it, and the chosen blue tones must harmonize with Very Peri to create a cohesive look. Additionally, the design needs to remain effective and appealing across various print and digital formats."
        ],
        "images": []
      },
      {
        "heading": "Summary",
        "paragraphs": [
          "The \"Pantone Very Peri Poster Design\" project is a contemporary exploration of color, form, and simplicity. By combining a soft periwinkle background, clean typography, and a delicate blue branch illustration, the poster celebrates Pantone’s Color of the Year 2022 in a fresh and minimalist way.",
          "This design exemplifies how thoughtful restraint and attention to detail can create a modern visual statement that is both memorable and versatile."
        ],
        "images": [
          "/images/cms/rgGNXJHIju2RXfdZpTAWjj3h7yI.jpeg",
          "/images/cms/cHLxOxAZNT9hNaHliAM0QcUBhI.jpeg"
        ]
      }
    ]
  },
  {
    "slug": "intenza-brand-boutique-e-gift-card-design",
    "category": "Graphic Design",
    "title": "Intenza Brand Boutique E-Gift Card Design",
    "description": "Created a modern and elegant e-gift card for Intenza Brand Boutique. Emphasized minimalism and premium aesthetics with a sleek black holder and a dynamic, fitness-inspired card image to reflect the brand’s active lifestyle identity.",
    "cover": "/images/cms/346Dg9EFyDG62n4PMiwIhATISNU.jpeg",
    "year": "2023",
    "industry": "Retail",
    "client": "Intenza Boutique",
    "duration": "5 weeks",
    "featured": false,
    "sections": [
      {
        "heading": "Problem",
        "paragraphs": [
          "In the competitive fitness and lifestyle market, brands often struggle to create e-gift cards that not only look premium but also resonate with their target audience’s aspirations.",
          "Many digital gift cards lack a distinctive identity, appearing generic or uninspired, which can undermine the perception of quality and brand value. Intenza Brand Boutique needed an e-gift card that would convey both elegance and the dynamic, active spirit of their brand."
        ],
        "images": [
          "/images/cms/twYs5TpNDOSj1RSC9CjNSfxL0.jpeg"
        ]
      },
      {
        "heading": "Solution",
        "paragraphs": [
          "The project focused on designing a modern and elegant e-gift card featuring a sleek black card holder to evoke a sense of luxury and exclusivity. The card itself incorporates dynamic, fitness-inspired imagery and minimalist design elements, reflecting the active lifestyle that defines the Intenza brand.",
          "The use of clean lines, refined typography, and a restrained color palette ensures that the card feels both contemporary and premium, making it an appealing gift choice for fitness enthusiasts."
        ],
        "images": [
          "/images/cms/54Q8QeVa217GvhmozfGEUFSFE1c.jpeg",
          "/images/cms/4RfvkBDYKCCeocDBYTEq5FMdYDY.jpeg"
        ]
      },
      {
        "heading": "Challenge",
        "paragraphs": [
          "One of the primary challenges was achieving a balance between minimalism and brand storytelling. The design needed to remain uncluttered and sophisticated while still communicating the energy and movement associated with an active lifestyle. Integrating fitness-inspired visuals without overwhelming the card’s elegant aesthetic required careful composition and attention to detail.",
          "Additionally, the e-gift card had to be versatile enough to look impressive across various digital platforms and screen sizes."
        ],
        "images": []
      },
      {
        "heading": "Summary",
        "paragraphs": [
          "The \"Intenza Brand Boutique E-Gift Card Design\" project successfully delivers a digital gift card that embodies both modern minimalism and the premium, active spirit of the brand. By combining a sleek black holder with a dynamic, fitness-inspired card image, the design stands out as both elegant and energetic.",
          "This project demonstrates how thoughtful design can elevate a simple product into a powerful brand statement, enhancing the gifting experience for both giver and recipient."
        ],
        "images": [
          "/images/cms/z3w3mzmmWHurhiPeiQFkXc5XPgU.jpeg"
        ]
      }
    ]
  },
  {
    "slug": "vistahaven-stunning-real-estate-template",
    "category": "Web Design",
    "title": "VistaHaven",
    "description": "VistaHaven is a sleek and modern real estate template designed to showcase luxury properties with elegance and sophistication.",
    "cover": "/images/cms/RzBOpbFyAywEXNkFbMTKVhq44.jpg",
    "year": "2025",
    "industry": "Real Estate",
    "client": "VistaHaven",
    "duration": "2 weeks",
    "featured": false,
    "sections": [
      {
        "heading": "Problem",
        "paragraphs": [
          "Luxury real estate agencies often struggle to find digital templates that truly reflect the elegance and exclusivity of their properties. Many existing templates are either too generic, cluttered, or lack the visual sophistication needed to appeal to high-end clientele. This results in missed opportunities to impress potential buyers and differentiate premium listings in a competitive market."
        ],
        "images": [
          "/images/cms/8l6y9Yi92OO5zND01Y1LUFafaY.jpg"
        ]
      },
      {
        "heading": "Solution",
        "paragraphs": [
          "VistaHaven was designed as a sleek and modern real estate template, purpose-built to elevate the presentation of luxury properties. The template features a clean layout, large high-resolution image galleries, and refined typography to create an immediate sense of sophistication.",
          "Interactive elements, such as virtual tours and property comparison tools, are seamlessly integrated to enhance user engagement. The color palette and design accents are carefully chosen to evoke a feeling of exclusivity and trust, ensuring that every property is showcased at its absolute best."
        ],
        "images": [
          "/images/cms/4Srg6lDELS0ije4ii4c3eZc2Sg.jpg",
          "/images/cms/H28VqI3rAtGLWcHKFYkjKyNnUo8.jpg"
        ]
      },
      {
        "heading": "Challenge",
        "paragraphs": [
          "The main challenge was to balance visual richness with usability. It was essential to create a template that looked luxurious without sacrificing loading speed or ease of navigation.",
          "Ensuring that the design remained responsive and visually compelling across all devices required meticulous attention to detail. Additionally, integrating advanced features like virtual tours and interactive maps while maintaining a minimalist aesthetic posed both design and technical hurdles."
        ],
        "images": []
      },
      {
        "heading": "Summary",
        "paragraphs": [
          "VistaHaven stands out as a stunning real estate template that perfectly blends elegance with modern functionality. By focusing on high-impact visuals, intuitive navigation, and premium interactive features, the template empowers real estate professionals to present luxury properties with the sophistication they deserve. This project demonstrates how thoughtful design can transform the digital real estate experience, making a lasting impression on discerning buyers."
        ],
        "images": [
          "/images/cms/ViCcevhh5VSNXEE6B9hZwgw.jpg"
        ]
      }
    ]
  },
  {
    "slug": "innovatetech-identity-rollout",
    "category": "Branding",
    "title": "InnovateTech Identity Rollout",
    "description": "Developed a brand identity for \"InnovateTech,\" including logo design, color palette, and visual style guide. Focused on conveying innovation and reliability across all branding elements.",
    "cover": "/images/cms/NbFTTP3LTcQw2s8139xTJnscc.jpeg",
    "year": "2025",
    "industry": "Tech",
    "client": "InnovateTech",
    "duration": "5 weeks",
    "featured": false,
    "sections": [
      {
        "heading": "Problem",
        "paragraphs": [
          "InnovateTech, as a forward-thinking technology company, faced the challenge of establishing a cohesive and memorable brand identity that would set it apart in a highly competitive industry.",
          "The existing branding lacked a unified visual language and failed to effectively communicate the company’s core values of innovation and reliability. This inconsistency made it difficult to build trust with clients and limited the brand’s impact across digital and print platforms."
        ],
        "images": [
          "/images/cms/HoN8akxh87AazL0TT4RCR3qWK2A.jpeg"
        ]
      },
      {
        "heading": "Solution",
        "paragraphs": [
          "The project centered on developing a comprehensive brand identity system for InnovateTech. This included designing a modern, versatile logo that visually represents both technological advancement and stability. A distinctive color palette was crafted to evoke a sense of innovation while maintaining a professional tone.",
          "The visual style guide detailed the use of typography, iconography, imagery, and layout principles to ensure brand consistency across all touchpoints. Each element was carefully chosen to reinforce the brand’s positioning as both cutting-edge and dependable."
        ],
        "images": [
          "/images/cms/AsCs8cGe5jDWkyOH4yAxcnD72MA.jpeg",
          "/images/cms/ueQw6lPziP3BS2aiiCDyayVsjkU.jpeg"
        ]
      },
      {
        "heading": "Challenge",
        "paragraphs": [
          "One of the main challenges was striking the right balance between a futuristic look and a trustworthy, approachable feel. The identity needed to appeal to both innovative startups and established enterprise clients. Ensuring that the visual elements worked harmoniously across a wide range of applications—from digital interfaces to printed collateral—required extensive testing and refinement."
        ],
        "images": []
      },
      {
        "heading": "Summary",
        "paragraphs": [
          "The \"InnovateTech Identity Rollout\" successfully established a bold and cohesive brand presence that communicates both innovation and reliability. Through a modern logo, a carefully curated color palette, and a detailed visual style guide, the new identity empowers InnovateTech to stand out in the technology sector.",
          "This project demonstrates the transformative power of strategic branding in building trust, recognition, and long-term value for a forward-looking company."
        ],
        "images": [
          "/images/cms/Tcgoo4tlFcuvOvKWnUOZS2EBk.jpeg"
        ]
      }
    ]
  }
];

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}
