// AUTO-GENERATED by scripts/build-data.mjs — do not edit by hand.
import type { Project } from "@/types";

export const projects: Project[] = [
  {
    "slug": "veritas-neural",
    "category": "AI / Deep Learning",
    "title": "Veritas Neural",
    "description": "A 4-modality deepfake detection engine using a 3-model ensemble achieving sub-1.5s inference latency on CPU-only hardware, with a Dockerized FastAPI backend and React frontend for fully local, privacy-preserving inference.",
    "cover": "/images/cms/w08JBQPFYIq2vr4OfcD9W6vxEug.jpeg",
    "year": "2025",
    "industry": "AI / Security",
    "client": "Personal Project",
    "duration": "8 weeks",
    "githubUrl": "https://github.com/1SoulHunter1/veritas-neural",
    "liveUrl": "https://veritas-neural.vercel.app",
    "featured": true,
    "sections": [
      {
        "heading": "Problem",
        "paragraphs": [
          "Deepfakes are becoming increasingly sophisticated, posing serious threats to media integrity, personal privacy, and public trust. Existing detection tools often rely on single-modality analysis and cloud-based inference, raising both accuracy and privacy concerns.",
          "There was a need for a multi-modal detection system that could analyze image, audio, video, and text simultaneously — all running locally to preserve user privacy."
        ],
        "images": [
          "/images/cms/7i3y7S8hh5RjwFKy8VAstpXwRLM.jpeg"
        ]
      },
      {
        "heading": "Solution",
        "paragraphs": [
          "Veritas Neural implements a 3-model ensemble architecture covering 4 modalities (vision, audio, text, and video). The system achieves sub-1.5s inference latency on CPU-only hardware, making it accessible without expensive GPU infrastructure.",
          "The backend is built with FastAPI and containerized via Docker, while the frontend uses React for an intuitive analysis dashboard. All inference runs locally, ensuring fully privacy-preserving deepfake detection."
        ],
        "images": [
          "/images/cms/lUKY3v1xTIvOuK62nRDiv3v87gc.jpeg",
          "/images/cms/uOR0RXqCvncnJFhOe6kPbaE9XLU.jpeg"
        ]
      },
      {
        "heading": "Challenge",
        "paragraphs": [
          "The primary challenge was achieving real-time inference across multiple modalities on CPU-only hardware. Balancing model accuracy with computational efficiency required careful architecture design, model quantization, and pipeline optimization.",
          "Ensuring consistent detection quality across diverse media types — from subtle face-swaps to AI-generated audio — demanded extensive cross-validation and benchmarking."
        ],
        "images": []
      },
      {
        "heading": "Summary",
        "paragraphs": [
          "Veritas Neural demonstrates that robust, multi-modal deepfake detection can run entirely on local hardware without sacrificing speed or accuracy. The 3-model ensemble approach provides defense-in-depth against evolving deepfake techniques.",
          "This project showcases end-to-end system design from model development through containerized deployment, proving that AI safety tools can be both powerful and privacy-preserving."
        ],
        "images": [
          "/images/cms/EITi5QTOPWfDXwQq1KDpx3O7xtc.jpeg",
          "/images/cms/IEHi1D1Kw4OMU5XdXNGshH3JpU.jpeg"
        ]
      }
    ]
  },
  {
    "slug": "linkedin-resume-ats-pipeline",
    "category": "AI Automation",
    "title": "LinkedIn Resume ATS Pipeline",
    "description": "An autonomous n8n workflow that scrapes LinkedIn internships via Apify, tailors ATS-optimized resumes with Google Gemini, compiles them to PDF via LaTeX-on-HTTP, and delivers a daily email digest — all without manual intervention.",
    "cover": "/images/cms/qbjsnnvP9w7UaA2syp36oUe8OSo.jpg",
    "year": "2025",
    "industry": "AI / Recruitment",
    "client": "Personal Project",
    "duration": "3 weeks",
    "githubUrl": "https://github.com/1SoulHunter1/Linkedin-Resume-ATS-Pipeline",
    "liveUrl": null,
    "featured": true,
    "sections": [
      {
        "heading": "Problem",
        "paragraphs": [
          "Manually customizing resumes and writing cold outreach emails for each internship posting doesn't scale beyond a few applications per week. Each role needs a tailored resume that passes ATS keyword filters and a personalized email that references the specific job — doing this by hand for dozens of roles daily is unsustainable."
        ],
        "images": [
          "/images/cms/GXMr7UYyjAl3Onda9G2r7zW7iD0.jpg"
        ]
      },
      {
        "heading": "Solution",
        "paragraphs": [
          "A six-stage n8n pipeline that runs daily on a schedule: it scrapes fresh LinkedIn job postings via an Apify actor, filters and deduplicates against a Supabase Postgres database, then feeds each posting through a Gemini-powered ATS optimizer that rewrites the resume — grounded strictly in real, verifiable experience.",
          "A second Gemini chain drafts a tailored cold outreach email for each role. The optimized resume is compiled to PDF via LaTeX-on-HTTP, uploaded to Google Drive, and a single daily HTML digest email summarizes every processed job with resume links and draft emails."
        ],
        "images": [
          "/images/cms/flsR6xqfDebWKrEfwDLKRuYU.jpg",
          "/images/cms/ZN2ayLXMera7geLQGafIWj94c.jpg"
        ]
      },
      {
        "heading": "Challenge",
        "paragraphs": [
          "Ensuring the LLM never fabricates experience was critical — the Gemini agent is constrained to only rephrase and reorder facts from the source resume, never invent new ones. Prompt engineering and output validation were iterated until the generated resumes consistently passed manual audit.",
          "Handling Apify actor timeouts, Gemini output parsing failures, and LaTeX compilation edge cases required a dedicated error-handling branch in the workflow. Supabase deduplication via a unique constraint on job_url prevents reprocessing, keeping costs predictable."
        ],
        "images": []
      },
      {
        "heading": "Summary",
        "paragraphs": [
          "The pipeline automates the full internship application lifecycle — from job discovery to ATS-optimized resume generation to cold email drafting — running autonomously on a daily schedule. It processes dozens of roles per day while ensuring every claim in the generated documents traces back to verified experience.",
          "Tech stack: n8n for orchestration, Apify for LinkedIn scraping, Google Gemini for resume tailoring and email generation, LaTeX-on-HTTP for PDF compilation, Supabase for deduplication, Google Drive for storage, and Gmail for daily digest delivery."
        ],
        "images": [
          "/images/cms/Rj0Ez5VU0m6neoNfeFEWpHKlG4.jpg"
        ]
      }
    ]
  },
  {
    "slug": "knowledge-graph-builder",
    "category": "NLP",
    "title": "Knowledge Graph Builder",
    "description": "An NLP pipeline using spaCy dependency parsing and coreference resolution, with Barnes-Hut force-directed graph rendering, NER-based clustering, and multi-format ingestion via a Streamlit dashboard.",
    "cover": "/images/cms/nTU7b0ZAdWdlqCI4mQ4tGTPpDs.jpeg",
    "year": "2025",
    "industry": "AI / Knowledge Management",
    "client": "Personal Project",
    "duration": "4 weeks",
    "githubUrl": "https://github.com/1SoulHunter1/knowledge-graph-builder",
    "liveUrl": null,
    "featured": true,
    "sections": [
      {
        "heading": "Problem",
        "paragraphs": [
          "Extracting structured knowledge from unstructured text documents is a fundamental challenge in NLP. Traditional approaches often miss implicit relationships between entities and struggle with coreference resolution across long documents.",
          "There was a need for an interactive tool that could ingest multiple document formats, extract entities and relationships, and visualize them as an explorable knowledge graph."
        ],
        "images": [
          "/images/cms/qWjMf5YLDsHPfWrxindJlbU8dZ0.jpg"
        ]
      },
      {
        "heading": "Solution",
        "paragraphs": [
          "The Knowledge Graph Builder implements a full NLP pipeline using spaCy for dependency parsing, named entity recognition, and coreference resolution. Extracted entities and relationships are rendered as an interactive force-directed graph using Barnes-Hut optimization for performance.",
          "The Streamlit dashboard provides multi-format document ingestion (PDF, DOCX, TXT), NER-based clustering for organizing related entities, and interactive graph exploration with filtering and search capabilities."
        ],
        "images": [
          "/images/cms/AQyIdhIsQfYxzXoj7uBtxQZiY.jpeg",
          "/images/cms/WzuGQPTkqf3192clNgTajkHRqk.jpeg"
        ]
      },
      {
        "heading": "Challenge",
        "paragraphs": [
          "Scaling graph rendering to handle thousands of nodes and edges required implementing Barnes-Hut force-directed layout optimization. Ensuring accurate coreference resolution across diverse document types demanded careful model tuning and evaluation."
        ],
        "images": []
      },
      {
        "heading": "Summary",
        "paragraphs": [
          "The Knowledge Graph Builder transforms unstructured text into structured, explorable knowledge graphs. By combining advanced NLP techniques with interactive visualization, the tool makes it easy to discover hidden relationships and patterns in large document collections.",
          "This project demonstrates practical NLP engineering — from pipeline design and entity extraction to graph algorithms and interactive dashboards."
        ],
        "images": [
          "/images/cms/V3dM8G5w3WsDaQWdlZHWXxDIrvw.jpeg"
        ]
      }
    ]
  },
  {
    "slug": "heart-disease-prediction",
    "category": "Machine Learning",
    "title": "Heart Disease Prediction",
    "description": "Compared six ML classifiers on the UCI Cleveland Heart Disease dataset, achieving 91.80% accuracy and 96.10% ROC-AUC with KNN after feature engineering and StratifiedKFold cross-validation.",
    "cover": "/images/cms/2nWXrWvPxxMHSpsOkNYf8KjzP7Q.jpeg",
    "year": "2024",
    "industry": "Healthcare / AI",
    "client": "Academic Project",
    "duration": "3 weeks",
    "githubUrl": "https://github.com/1SoulHunter1/heart-disease-prediction",
    "liveUrl": null,
    "featured": true,
    "sections": [
      {
        "heading": "Problem",
        "paragraphs": [
          "Heart disease remains one of the leading causes of death globally. Early prediction using patient clinical data can significantly improve outcomes, but selecting the right ML approach and properly evaluating model performance is critical for reliable predictions."
        ],
        "images": [
          "/images/cms/DLbVxsYll4feLhrOA8Pq4MPaVhs.jpeg"
        ]
      },
      {
        "heading": "Solution",
        "paragraphs": [
          "This project systematically compared six machine learning classifiers — Logistic Regression, Decision Tree, Random Forest, SVM, KNN, and Naive Bayes — on the UCI Cleveland Heart Disease dataset. Feature engineering techniques were applied to optimize model inputs.",
          "StratifiedKFold cross-validation ensured robust evaluation across class distributions. The KNN classifier achieved the best performance with 91.80% accuracy and 96.10% ROC-AUC, demonstrating strong predictive capability."
        ],
        "images": [
          "/images/cms/7vdKfhDeY9XcYH1lKpvTLMT0gb8.jpeg",
          "/images/cms/axOfqlt1OrF9ee8oXYdukDuM99U.jpeg"
        ]
      },
      {
        "heading": "Challenge",
        "paragraphs": [
          "The main challenge was ensuring fair model comparison through consistent preprocessing, hyperparameter tuning, and cross-validation strategies. Handling class imbalance and selecting meaningful evaluation metrics beyond accuracy required careful statistical analysis."
        ],
        "images": []
      },
      {
        "heading": "Summary",
        "paragraphs": [
          "This project provides a rigorous comparison of classical ML classifiers for heart disease prediction, establishing KNN as the top performer on the UCI Cleveland dataset. The systematic evaluation methodology ensures reproducible and trustworthy results.",
          "The work demonstrates strong foundations in ML experimentation — from data preprocessing and feature engineering to model selection and statistical evaluation."
        ],
        "images": [
          "/images/cms/iS2DgXxnjtQqDJ5KVOdKGQLXgD8.jpeg",
          "/images/cms/8sl9Ujll2IskiALuyKBBhJlknJ4.jpeg"
        ]
      }
    ]
  },
  {
    "slug": "agentflow",
    "category": "AI / Productivity",
    "title": "AgentFlow",
    "description": "An AI-powered automation workspace that connects chat models, research agents, and integrations into a unified dashboard — a personal LangDock + Notion + Zapier built with Next.js 15, Prisma, PostgreSQL, and Groq.",
    "cover": "/images/cms/346Dg9EFyDG62n4PMiwIhATISNU.jpeg",
    "year": "2025",
    "industry": "AI / Productivity",
    "client": "Personal Project",
    "duration": "6 weeks",
    "githubUrl": "https://github.com/1SoulHunter1/AgentFlow-AI_Automation_Platform",
    "liveUrl": null,
    "featured": false,
    "sections": [
      {
        "heading": "Problem",
        "paragraphs": [
          "Developers, analysts, and creators juggle multiple tools for AI chat, web research, document summarization, and knowledge management. Switching between standalone LLM interfaces, search tools, and Notion means fragmented workflows and lost context.",
          "There was a need for a single workspace where AI agents could collaborate — research, summarize, and push results directly into productivity tools without manual copy-pasting."
        ],
        "images": [
          "/images/cms/U0I500EmGOZ2lvygkGIvmr13JU.jpeg"
        ]
      },
      {
        "heading": "Solution",
        "paragraphs": [
          "AgentFlow provides a real-time streaming chat interface powered by Groq AI (Llama 3.3 / Gemma), with three specialized agents: a Web Search Agent (Tavily API), a Summarizer Agent, and a Deep Research Agent that performs multi-layer contextual analysis.",
          "The platform integrates directly with the Notion API for seamless database sync, supports file uploads (.pdf, .docx, .csv, .txt) with automatic extraction and summarization, and persists conversations via Prisma ORM and PostgreSQL."
        ],
        "images": [
          "/images/cms/mBc2xUjTRVxlcztYHtgXYF11o.jpeg",
          "/images/cms/HNVCqnaFAfiDAhkxkg4SjB5c3w.jpeg"
        ]
      },
      {
        "heading": "Challenge",
        "paragraphs": [
          "Orchestrating multiple AI agents with different capabilities while maintaining coherent conversation state required careful API route design and token budget management across Groq models. The real-time streaming chat needed reliable markdown rendering and conversation persistence.",
          "Integrating with the Notion API demanded handling rate limits, schema mapping between Notion’s block structure and the app’s internal data model, and ensuring bidirectional sync without data loss."
        ],
        "images": []
      },
      {
        "heading": "Summary",
        "paragraphs": [
          "AgentFlow demonstrates how multi-agent AI systems can unify productivity workflows in a single dashboard. By combining fast LLM inference via Groq, web search via Tavily, document processing, and Notion integration, the platform delivers an intelligent workspace that scales with the user.",
          "Tech stack: Next.js 15, TypeScript, TailwindCSS, shadcn/ui, Groq AI, Tavily Search, Notion API, Prisma ORM, PostgreSQL, deployed on Vercel."
        ],
        "images": [
          "/images/cms/rgGNXJHIju2RXfdZpTAWjj3h7yI.jpeg",
          "/images/cms/cHLxOxAZNT9hNaHliAM0QcUBhI.jpeg"
        ]
      }
    ]
  },
  {
    "slug": "fittrack-fitness-tracker",
    "category": "Mobile App",
    "title": "FitTrack — Fitness Tracker App",
    "description": "A Flutter fitness tracking app with Material 3 UI, animated charts, dual database support (SQLite offline + Firebase cloud), and Provider state management — built during a CodeAlpha internship.",
    "cover": "/images/cms/RzBOpbFyAywEXNkFbMTKVhq44.jpg",
    "year": "2025",
    "industry": "Health / Fitness",
    "client": "CodeAlpha Internship",
    "duration": "4 weeks",
    "githubUrl": "https://github.com/1SoulHunter1/CodeAlpha_Fitness_Tracker_App",
    "liveUrl": null,
    "featured": false,
    "sections": [
      {
        "heading": "Problem",
        "paragraphs": [
          "Most fitness tracking apps are either bloated with features most users never touch, or locked into a single data storage model — forcing users to choose between offline-only access and cloud backup. There was a need for a clean, focused fitness tracker that lets users switch between local and cloud storage seamlessly."
        ],
        "images": [
          "/images/cms/DLbVxsYll4feLhrOA8Pq4MPaVhs.jpeg"
        ]
      },
      {
        "heading": "Solution",
        "paragraphs": [
          "FitTrack is a Flutter app with a polished Material 3 UI featuring a modern dashboard with daily steps, weekly calorie tracking, and progress goals — all visualized through animated charts using fl_chart.",
          "The app uses a clean architecture with an abstract DatabaseService interface, allowing users to switch between SQLite (offline) and Cloud Firestore (cloud backup) without changing any application logic. Provider handles state management, optimized for 120Hz displays."
        ],
        "images": [
          "/images/cms/7vdKfhDeY9XcYH1lKpvTLMT0gb8.jpeg",
          "/images/cms/axOfqlt1OrF9ee8oXYdukDuM99U.jpeg"
        ]
      },
      {
        "heading": "Challenge",
        "paragraphs": [
          "Designing the dual database abstraction was the core architectural challenge — the service layer needed to be truly interchangeable so swapping from SQLite to Firestore required changing a single line, not rewriting data access logic. Ensuring consistent data models and query patterns across both backends required careful interface design.",
          "Achieving smooth 120Hz animations on the dashboard charts while maintaining responsive UI during database operations required optimized Provider patterns and efficient widget rebuilds."
        ],
        "images": []
      },
      {
        "heading": "Summary",
        "paragraphs": [
          "FitTrack delivers a focused, well-architected fitness tracker that prioritizes clean code and user experience over feature bloat. The dual database architecture demonstrates clean separation of concerns, and the Material 3 UI with animated charts provides a polished, modern feel.",
          "Tech stack: Flutter 3.x, Dart, Provider, SQFlite, Cloud Firestore, fl_chart, Google Fonts (Poppins), Shared Preferences. Supports Android and iOS."
        ],
        "images": [
          "/images/cms/iS2DgXxnjtQqDJ5KVOdKGQLXgD8.jpeg",
          "/images/cms/8sl9Ujll2IskiALuyKBBhJlknJ4.jpeg"
        ]
      }
    ]
  }
];

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}
